# Dot at end of line makes it clearer that the line is not done
Layout/DotPosition:
  EnforcedStyle: trailing

# Do not require empty lines between one-line defs.
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Require lines to fit in pull requests.
Metrics/LineLength:
  Max: 92
