# Dot at end of line makes it clearer that the line is not done
Style/DotPosition:
  EnforcedStyle: trailing

# Require lines to fit in pull requests.
Metrics/LineLength:
  Max: 92

# Do not require empty lines between one-line defs.
Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
